# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WebSocketDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'SocketRocket'
  pod 'AFNetworking','~>4.0.0'
  pod 'MJExtension', '~> 3.2.1'
  pod 'Starscream', '~> 4.0.0'

  # Pods for WebSocketDemo

  target 'WebSocketDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebSocketDemoUITests' do
    # Pods for testing
  end

end
